disabled_rules:
  - line_length
  - force_cast
  - force_try
type_body_length:
- 200 # warning
- 400 # error
variable_name:
  max_length:
    - 60 # warning
    - 80 # error
  min_length:
    - 1 # warning
    - 0 # error
function_body_length:
- 100 # warning
- 200 # error
excluded:
  - Frameworks
  - Carthage